[project]
name = "personal-finance-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ayomide Adeakin", email = "ayomideadeakin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "sqlalchemy>=2.1.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
personal-finance-planner = "personal_finance_planner:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
